[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "bonobench"
version = "0.0.3.dev0"
authors = [
  { name="Lennart Schäpermeier", email="lennart.schaepermeier@uni-muenster.de" },
]
description = "Bi-objective Numerical Optimization Benchmark Problems"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]
dependencies = [
  "numpy>=2.4.0",
  "sortedcontainers>=2.4.0",
  "matplotlib>=3.10.8",
  "moocore>=0.1.10"
]

[project.urls]
Homepage = "https://github.com/schaepermeier/bonobench"
Issues = "https://github.com/schaepermeier/bonobench/issues"
